[package]
name = "potential"
version = "0.1.0"
authors = ["Joe Loach <joe.gloach@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# window / rendering
miniquad = "=0.3.0-alpha.37"
# gui
egui = "0.15.0"
egui-miniquad = "0.7.0"
