[package]
name = "potential"
version = "0.1.0"
authors = ["Joe Loach <joe.gloach@gmail.com>"]
resolver = "2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.8.0"
ultraviolet = "0.8.1"
winit = "0.26"

# web deps
[target.'cfg(target_arch = "wasm32")'.dependencies]
wgpu = { version = "0.11", features = ["webgl"] }
wasm-bindgen = "0.2.78"
wasm-bindgen-futures = "0.4"
web-sys = "0.3"

# native deps
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wgpu = "0.11"
pollster = "0.2"
