[package]
name = "builder"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.133"
serde_derive = "1.0.133"
spirv-builder = { git = "https://github.com/EmbarkStudios/rust-gpu" }
toml = "0.5.8"
